spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/litfeed_base
spring.datasource.username=root
spring.datasource.password=Tae301995@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
